### PR TITLE
fix: max guess limit and guess count display

### LINKED ISSUE #18: Incorrect Max Guess Count and Loss Processing
There should be 10 guesses before the player loses, but the player gets 11.
If the player guesses correctly on the eleventh guess, they receive 2 loss messages.
image

### PR DESCRIPTION
**Pull request by TheVanadium**
Fixes #18 

Limits the total amount of guesses to 10, as it should
Adds a catch to ensure the lose message does not show up if the game is won on the same turn the guess limit is reached
Limits updating the "guess-counter" div when the player has won; there is no additional increment in the guess count to display

### CODE REVIEW

**Comment by pavo-etc** [comment]
Will test soon

File: app/static/js/processGuess.js [hunk 1]
```diff
@@ -311,9 +311,19 @@ function processGuess(guess) {
...
 
+  // only needs to progress to the next guess if the game is not over
+  // if guessCount reaches maxGuesses, the game is over
+  let currentGuessNumber = min(guessCount + 1, maxGuesses);
+  document.getElementById("guess-counter").innerText = currentGuessNumber;
+
   return { isCorrect: false, matchmap: correctSlots };
 }
 
+function min(a, b) {
```
Comment (pavo-etc) [inline app/static/js/processGuess.js:322]: Can just use Math.min(), don't need this function

**Review by pavo-etc — CHANGES_REQUESTED** [review]

**Comment by pavo-etc** [comment]
Seems all good in testing, just remove the min function and I'll merge it

**Comment by TheVanadium** [comment]
> Seems all good in testing, just remove the min function and I'll merge it

Done

**Review by pavo-etc — APPROVED** [review]
